### ISSUE TITLE
MyOnlineService.de Done scraping vattenfall: CHECK_ACCOUNT

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#2093]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 5ff09d
Git sha1: 450d51
jvm_id: 09543b67-8bcb-48c4-bfba-d09127a03f36
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.140.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.5
now: 2019-12-18T14:15:24.830394+01:00
retriever_nice_message: Aucun contrat actif
retriever_stack: Traceback (most recent call last):
  File "/sources/scraper/scraper.py", line 200, in scrap
    self.collect_documents(document)
  File "/sources/scraper/scraper.py", line 138, in collect_documents
    scraper.run(meta)
  File "/sources/scraper/scraperengine.py", line 299, in run
    raise e
  File "/sources/scraper/scraperengine.py", line 289, in run
    self._steps(meta['steps'])
  File "/sources/scraper/scraperengine.py", line 2199, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2179, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 2730, in _phase
    self._steps(steps)
  File "/sources/scraper/scraperengine.py", line 2199, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2179, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 1958, in _if
    self._steps(_else)
  File "/sources/scraper/scraperengine.py", line 2199, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2179, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 567, in _raise
    raise StatusError(status, msg)
scraper.errors.StatusError: CHECK_ACCOUNT: Aucun contrat actif

scraping_transaction: 4ce3b20109b94ada81489ab0228463e6
external_status_code: CHECK_ACCOUNT
contractsMetadata: []
credentials_are_invalid: false
account_needs_cgu: true
captcha_not_solved: false
idp_not_available: false
idp_failure: false
request_user_input: false
result_is_final: true
current_phase: profile
user_info: {}
external_registration_date: 2019-12-18T13:14:33.447000+00:00
external_start_date: 2019-12-18T13:14:33.689000+00:00
external_end_date: 2019-12-18T13:15:24.030000+00:00
idp_group_id: vattenfall
scraper_id: c334df6b-492c-411a-8ee1-e58ec905c9b5
sharing_flow_id: 25353765-62f4-4226-bc22-e835b9eb66ad
client_id: prd_MiTrust_Demo_MyOnlineService.de
retriever_url: https://prd-retriever-public-api.azurewebsites.net/2.0

**Comment by andradeje** [comment]
jp

**Comment by andradeje** [comment]
ça ressemble à un problème de chargement et non un check account
