### ISSUE TITLE
NewDataSourcesProgram_de Done scraping ruv: SCRAPER_UNEXPECTED_HTML

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#3265]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 0bb505
Git sha1: cc7a8c
jvm_id: fe8268c2-78ff-406c-943d-5e5c5cc6c69c
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.136.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.5
now: 2020-01-11T13:41:23.792426+01:00
retriever_nice_message: element click intercepted: Element <button type="submit" id="loginBtn" class="btn btn-primaer" onclick="ruvui.meinerv.modules.login.login();return false;">...</button> is not clickable at point (168, 481). Other element would receive the click: <span>...</span>
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)
retriever_stack: Traceback (most recent call last):
  File "/sources/scraper/scraperengine.py", line 1253, in _click
    elem.click()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="submit" id="loginBtn" class="btn btn-primaer" onclick="ruvui.meinerv.modules.login.login();return false;">...</button> is not clickable at point (168, 481). Other element would receive the click: <span>...</span>
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/scraper/scraper.py", line 200, in scrap
    self.collect_documents(document)
  File "/sources/scraper/scraper.py", line 138, in collect_documents
    scraper.run(meta)
  File "/sources/scraper/scraperengine.py", line 300, in run
    raise e
  File "/sources/scraper/scraperengine.py", line 290, in run
    self._steps(meta['steps'])
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 2737, in _phase
    self._steps(steps)
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 1297, in _click
    raise ScraperUnexpectedHtml('_click', e.msg)
scraper.errors.ScraperUnexpectedHtml: _click: element click intercepted: Element <button type="submit" id="loginBtn" class="btn btn-primaer" onclick="ruvui.meinerv.modules.login.login();return false;">...</button> is not clickable at point (168, 481). Other element would receive the click: <span>...</span>
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)

scraping_transaction: 17495e41094c4f4e99ab9ff1b4ce9cfc
external_status_code: SCRAPER_UNEXPECTED_HTML
contractsMetadata: []
credentials_are_invalid: false
account_needs_cgu: false
captcha_not_solved: false
idp_not_available: false
idp_failure: true
request_user_input: false
result_is_final: true
current_phase: login
user_info: {}
external_registration_date: 2020-01-11T12:41:12.579000+00:00
external_start_date: 2020-01-11T12:41:13.652000+00:00
external_end_date: 2020-01-11T12:41:23.487000+00:00
idp_group_id: ruv
scraper_id: 1968063f-b164-49c9-8182-8c0f524219a2
sharing_flow_id: 4c9e4107-a68c-481f-bb92-10ee47921725
client_id: prd_MiTrust_NewDataSourcesProgram_de
retriever_url: https://prd-retriever-public-api.azurewebsites.net/2.0
NewDataSourcesProgram_: true

**Comment by matthieub-mitrust** [comment]
jp
