### ISSUE TITLE
nebenan.de Done scraping entega: SCRAPER_UNEXPECTED_HTML

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#3842]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 8b85d1
Git sha1: b29bd4
jvm_id: 3d27d848-e812-499e-adf9-9b4901943179
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.136.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.5
now: 2020-01-18T14:00:18.439850+01:00
retriever_nice_message: _input: Can't find element {'type': 'css', 'value': '#username'}
retriever_stack: Traceback (most recent call last):
  File "/sources/scraper/scraperengine.py", line 380, in _get
    ec.visibility_of_element_located((search_type, value))
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/scraper/scraperengine.py", line 1382, in _input
    elem = self._get(element)
  File "/sources/scraper/scraperengine.py", line 385, in _get
    raise NoSuchElementException(element)
selenium.common.exceptions.NoSuchElementException: Message: {'type': 'css', 'value': '#username'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/scraper/scraper.py", line 200, in scrap
    self.collect_documents(document)
  File "/sources/scraper/scraper.py", line 138, in collect_documents
    scraper.run(meta)
  File "/sources/scraper/scraperengine.py", line 300, in run
    raise e
  File "/sources/scraper/scraperengine.py", line 290, in run
    self._steps(meta['steps'])
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 2737, in _phase
    self._steps(steps)
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 1384, in _input
    raise ScraperUnexpectedHtml(message="_input: Can't find element {}".format(element))
scraper.errors.ScraperUnexpectedHtml: None: _input: Can't find element {'type': 'css', 'value': '#username'}

scraping_transaction: 1ea0e88000a84b17a1d3b2e3d161c2c0
external_status_code: SCRAPER_UNEXPECTED_HTML
contractsMetadata: []
credentials_are_invalid: false
account_needs_cgu: false
captcha_not_solved: false
idp_not_available: false
idp_failure: true
request_user_input: false
result_is_final: true
current_phase: login
user_info: {}
external_registration_date: 2020-01-18T12:59:45.957000+00:00
external_start_date: 2020-01-18T12:59:46.760000+00:00
external_end_date: 2020-01-18T13:00:18.139000+00:00
idp_group_id: entega
scraper_id: 4731b71c-fb21-4763-81c5-fd4afcae3f7b
sharing_flow_id: 1ecd9650-db91-4684-81a0-05715a6b7f6d
client_id: 6df67293bf13afa59c1a78ab8b633ab4
retriever_url: https://prd-retriever-public-api.azurewebsites.net/2.0

**Comment by andradeje** [comment]
jp
