### ISSUE TITLE
O2 Click en timeout

### ISSUE THREAD

**Issue by matthieub-mitrust** [cormoran-io/retriever-cases#3967]
mitrust.env: prd
spring.application.name: retriever-proxy
Azure id: 8b85d1
Git sha1: b29bd4
jvm_id: e42ccbaa-03f2-4d87-a92a-7d049f2c3752
user_name: null
user_class: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken
user_authorities: [ROLE_PRD-DATASHARING-RETRIEVER_PROXY-API]
class_name: io.mitrust.retriever_proxy.mvc.RetrieverProxyControllerHelper
EndUser IP: 40.89.140.0
Request Path: https://prd-retriever-proxy.azurewebsites.net/internal/retriever/v1/getLatestUserInfo
User-Agent: Java/11.0.5
now: 2020-01-20T11:14:51.698843+01:00
retriever_nice_message: _click: timeout
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)
retriever_stack: Traceback (most recent call last):
  File "/sources/scraper/scraperengine.py", line 1265, in _click
    page_reloaded = self.browser.execute_script(test_reload_script)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/scraper/scraper.py", line 200, in scrap
    self.collect_documents(document)
  File "/sources/scraper/scraper.py", line 138, in collect_documents
    scraper.run(meta)
  File "/sources/scraper/scraperengine.py", line 300, in run
    raise e
  File "/sources/scraper/scraperengine.py", line 290, in run
    self._steps(meta['steps'])
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 2737, in _phase
    self._steps(steps)
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 1957, in _if
    self._steps(_then)
  File "/sources/scraper/scraperengine.py", line 2206, in _steps
    self._step(step)
  File "/sources/scraper/scraperengine.py", line 2186, in _step
    ret = getattr(self, '_' + functor)(**args)
  File "/sources/scraper/scraperengine.py", line 1307, in _click
    raise ScraperUnexpectedHtml(message="_click: {}".format(e.msg))
scraper.errors.ScraperUnexpectedHtml: None: _click: timeout
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)

scraping_transaction: c5044a99448643d58a9aed67d784aca8
external_status_code: SCRAPER_UNEXPECTED_HTML
contractsMetadata: []
credentials_are_invalid: false
account_needs_cgu: false
captcha_not_solved: false
idp_not_available: false
idp_failure: true
request_user_input: false
result_is_final: true
current_phase: mitrust-data
user_info: {}
external_registration_date: 2020-01-20T10:13:57.350000+00:00
external_start_date: 2020-01-20T10:13:58.174000+00:00
external_end_date: 2020-01-20T10:14:50.480000+00:00
idp_group_id: o2
scraper_id: d9d3fb7b-9557-4e7e-aaf1-674411a1ebfc$ndsp
sharing_flow_id: 8700f488-43ad-42eb-8321-51dbb7ce9d4d
client_id: 6df67293bf13afa59c1a78ab8b633ab4
retriever_url: https://prd-retriever-public-api.azurewebsites.net/2.0

**Comment by matthieub-mitrust** [comment]
jp

**Comment by matthieub-mitrust** [comment]
[2020-01-20 10:14:28.547700] [2.4.1] -> click {'element': {'type': 'css', 'value': 'div.side-nav-contract-static-menu > ul > li:nth-child(2) > a'}, 'options': {'use_js': True}}
[2020-01-20 10:14:48.722403] ERROR: Click on {'type': 'css', 'value': 'div.side-nav-contract-static-menu > ul > li:nth-child(2) > a'} : timeout
  (Session info: chrome=79.0.3945.88)
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1066-azure x86_64)
[2020-01-20 10:14:48.722898] Traceback (most recent call last):
